# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_depth <- function(X, data) {
    .Call(`_StableMCD_proj_depth`, X, data)
}

lts <- function(X, y, alphas) {
    .Call(`_StableMCD_lts`, X, y, alphas)
}

bootstrap_lts <- function(X, y, alphas, B = 50L) {
    .Call(`_StableMCD_bootstrap_lts`, X, y, alphas, B)
}

rcpp_hello_world <- function() {
    .Call(`_StableMCD_rcpp_hello_world`)
}

irls_glm <- function(X, y, weights, family, tol = 1e-8, max_iter = 25L) {
    .Call(`_StableMCD_irls_glm`, X, y, weights, family, tol, max_iter)
}

var_stab_res <- function(X, y, weights, family, beta) {
    .Call(`_StableMCD_var_stab_res`, X, y, weights, family, beta)
}

trimmed_glm <- function(X, y, alphas, family, weights) {
    .Call(`_StableMCD_trimmed_glm`, X, y, alphas, family, weights)
}

bootstrap_glm <- function(X, y, alphas, family, weights, B = 50L) {
    .Call(`_StableMCD_bootstrap_glm`, X, y, alphas, family, weights, B)
}

