# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_depth <- function(X, data, style) {
    .Call(`_StableMCD_proj_depth`, X, data, style)
}

lts <- function(X, y, alphas) {
    .Call(`_StableMCD_lts`, X, y, alphas)
}

get_insta <- function(is_outlier1, is_outlier2, h) {
    .Call(`_StableMCD_get_insta`, is_outlier1, is_outlier2, h)
}

trimean <- function(x) {
    .Call(`_StableMCD_trimean`, x)
}

bootstrap_lts <- function(X, y, alphas, B = 100L) {
    .Call(`_StableMCD_bootstrap_lts`, X, y, alphas, B)
}

irls_glm <- function(X, y, weights, family, tol = 1e-8, max_iter = 25L) {
    .Call(`_StableMCD_irls_glm`, X, y, weights, family, tol, max_iter)
}

var_stab_res <- function(X, y, weights, family, beta) {
    .Call(`_StableMCD_var_stab_res`, X, y, weights, family, beta)
}

trimmed_glm <- function(X, y, alphas, family, weights) {
    .Call(`_StableMCD_trimmed_glm`, X, y, alphas, family, weights)
}

bootstrap_glm <- function(X, y, alphas, family, weights, B = 100L) {
    .Call(`_StableMCD_bootstrap_glm`, X, y, alphas, family, weights, B)
}

